name: Update inputs
on:
  schedule:
    - cron: 0 0 * * *

jobs:
  nix-update:
    uses: rake5k/flake-commons/.github/workflows/nix-update.yml@main
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
